void exception_init();
void exception_handle();
